repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.3.0
    hooks:
      - id: golangci-lint
